[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = 'Goyo'


[[plugins]]
repo = 'junegunn/limelight.vim'
on_cmd = 'Limelight'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['python','javascript','jsx','javascript.jsx','html','css','go','vim','toml','html','typescript']
hook_source = 'let g:rainbow_active = 1'


[[plugins]]
repo = 'airblade/vim-rooter'
on_path = '.*'
hook_source = 'let g:rooter_silent_chdir = 1'


[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_source = 'source ~/.vim/config/defx.vim'


