source ~/.vim/config/pluginrc.vim
set nocompatible
set path+=**
set updatetime=5000
set directory=~/tmp,/tmp
set foldmethod=indent
set foldlevel=99
set autoindent
set encoding=utf-8
set clipboard+=unnamed  " use the clipboards of vim and win
" set paste               " Paste from a windows or from vim
set go+=a               " Visual selection automatically copied to the clipboard
set number
set relativenumber
set showtabline=2
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b
set nowrap
set fileformat=unix
set cindent
set colorcolumn=80
set tabstop=2
set shiftwidth=2
set softtabstop=2
set showmatch
set scrolloff=5
set laststatus=2
set fenc=utf-8
set backspace=2
set mouse=a
set selection=exclusive
set selectmode=mouse,key
set matchtime=5
set ignorecase
set incsearch
set hlsearch
set expandtab
set whichwrap+=<,>,h,l
set autoread
set cursorline
set cursorcolumn
set history=200
set fixendofline
" set conceallevel=0
" set transparency=10

let g:vim_json_syntax_conceal = 0
let python_highlight_all=1
set t_Co=256

set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
  \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
  \,sm:block-blinkwait175-blinkoff150-blinkon175

set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark
colorscheme dracula

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/venv/*,*/node_modules/*
let g:pymode_python = 'python3'

source ~/.vim/config/nerdcommenter.vim



let g:rooter_silent_chdir = 1

" leaderf configuration "
let g:Lf_ShortcutF = '<c-p>'
let g:Lf_CommandMap = {'<Tab>': ['<ESC>']}
let g:Lf_DefaultMode = 'NameOnly'
let g:Lf_WindowHeight = 0.3
let g:Lf_WorkingDirectoryMode = 'Ac'





let g:jsx_ext_required = 0

" autocmd FileType typescript,html,javascript.jsx set ts=2 | set shiftwidth=2
autocmd FileType python set ts=4 | set shiftwidth=4 | set softtabstop=4
let g:SuperTabDefaultCompletionType = "<c-n>"
let g:user_emmet_install_global = 0
autocmd FileType html,css,javascript.jsx,vue.html.javascript.css,vue EmmetInstall

"--------------------mapping-------
source ~/.vim/config/mapping.vim
"--------------------terminal-------
source ~/.vim/config/terminal.vim

let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']

autocmd FileType vue syntax sync fromstart
" autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html.javascript.css


" ------------startify configuration----------------
let g:startify_change_to_vcs_root = 1
let g:startify_change_to_dir = 0
let g:startify_custom_header = ['']
let g:startify_enable_special = 0

" -------------------------ctags------------------"
source ~/.vim/config/ctags.vim

:py3 sys.executable='/usr/local/bin/python3'
let g:python3_host_prog  = '/usr/local/Cellar/python/3.7.3/bin/python3'
let g:python_host_prog  = '/usr/bin/python'
let g:loaded_python_provider = 1

let g:rainbow_active = 1

"----------------------coc----------------------------"
source ~/.vim/config/coc.vim

autocmd FileType json syntax match Comment +\/\/.\+$+
"


" auto pair
let g:AutoPairsMapCh = 0
let g:AutoPairsMapCR = 1




" vim-workspace
let g:workspace_autosave = 0
let g:workspace_persist_undo_history = 0
let g:workspace_autosave_untrailspaces = 0
let g:workspace_session_directory = $HOME . '/.vim/sessions/'



let g:highlightedyank_highlight_duration = 500


source ~/.vim/config/defx.vim

let $NVIM_COC_LOG_LEVEL = 'debug'
" let g:coc_node_args = ['--nolazy', '--inspect-brk=6046']
"

" goyo and limelight

let g:goyo_width=100
let g:goyo_linenr=1
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!



" -------lightline-----------
source ~/.vim/config/lightline.vim
source ~/.vim/config/abbr.vim
